### ISSUE TITLE
Roll modifier bonuses are factored into bonus stacking rules even when disabled.

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt-starfinder/foundryvtt-starfinder#431] opened 2021-08-07 22:38 UTC
Steps to reproduce:

1. Create a small constant modifier (e.g +1)
2. Create a larger roll formula modifier (e.g +4) and disable it.
3. The affected stat will have no difference; the +1 is ignored because it's smaller than the +4, and the +4 is ignored because it is disabled.

Tested on insight and divine bonuses, functions the same.

**Comment by TimToxopeus** [comment] 2022-01-16 15:16
This might have been caused by the bug where all modifiers were always taken into account, regardless of their enabled state. Could you verify this has been fixed once Starfinder v0.18 is released? Or earlier, if you are able to check out the development branch.

**Comment by LebombJames** [comment] 2022-01-16 15:38
With a +4 situational modifier and a +1 constant modifier, both insight: On the sheet, the +1 is added when the +4 is disabled, and not when the +4 is enabled. 

This will get a bit weird with something like an operative with bonuses that only apply in certain situations: E.g, if they have constant +1 and a situational +4, when that +4 isn't applicable and it is turned off on the roll dialogue, the +1 is ignored.

That makes sense since the +1 isn't on the sheet, but is in fact incorrect. Ideally, the formula for that specific roll would change by +3 depending on if the situational modifier was enabled or not.

(This was on 0.18 btw)

**Closed** 2023-04-18 23:30 UTC
